# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apiclinicstock:
    build: /WebApi
    ports:
      - 5124:5124
    depends_on: 
      - mssql
      - redis
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConexaoPadrao=Server=mssql;Database=ClinicStock;User Id=sa;Password=Password123!;Encrypt=False
      - Redis__ConnectionString=redis:6379,password=my-password

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - app-network


  mssqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - mssql-data:/var/opt/mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    networks:
      - app-network
    volumes:
      - ./scripts:/usr/src/app
    working_dir: /usr/src/app
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
    depends_on:
      - mssqldata
volumes:
  mssql-data:


networks:
  app-network:
    driver: bridge
