# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apiclinicstock:
    image: apiclinicstock
    build:
      context: .
      dockerfile: src/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5124:5124
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
